<% creds = JSON.parse(ENV['VCAP_SERVICES'])[ENV['SERVICE_NAME']].first['credentials'] %>

development:
  clients:
    default:
      database: <%= creds['default_database'] %>
      hosts: <%= creds['hosts'].to_json %>
      options:
        raise_not_found_error: false
        user: <%= creds['username'] %>
        password: <%= creds['password'] %>

test:
  clients:
    default:
      database: a9s_mongodb_app_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: primary
        max_pool_size: 1

production:
  clients:
    default:
      database: <%= creds['default_database'] %>
      hosts: <%= creds['hosts'].to_json %>
      options:
        raise_not_found_error: false
        user: <%= creds['username'] %>
        password: <%= creds['password'] %>
